default:
    IMAGE_SIZE: 128
    N_CHANNELS: 3
    USE_HILL: True
    NORM_IMAGES: True
    NUM_CLASSES: 1
    CLASS_NAME: "Structures"

    EPOCHS: 5
    N_STEPS: 1
    BATCH_SIZE: 2
    DROPOUT: 0.20

    AMT_TRAIN: 280
    AMT_VAL: 50
    
    # Image Augmentation
    USE_AUGMENTATION: True
    AUGMENT_ARGS: !expr list(rotation_range=180,
                             width_shift_range=0.1,
                             height_shift_range=0.1,
                             zoom_range=0.2,
                             fill_mode="reflect",
                             horizontal_flip=TRUE,
                             vertical_flip=TRUE)

    # Image and mask locations for single image inifinite chip generator
    TRAIN_IMG: 'C:/Project_files/SARA/TIFF/SARA_1ft/SARA_1ft_CROP.tif'
    TRAIN_MSK: 'C:/Project_files/SARA/IMAGE_TILES/binary_masks_1ft/SARA_2_mask.tif'
    VAL_IMG:   'C:/Project_files/SARA/TIFF/SARA_1ft/SARA_1ft_CROP2_TEST.tif'
    VAL_MSK:   'C:/Project_files/SARA/IMAGE_TILES/binary_masks_1ft_Crop2/SARA_2_mask.tif'
    
    SAVE_WEIGHTS_DIR: 'C:/Users/matthew.d.harris/ZF_UNET_224/weights'

    # Maximum number of ground truth instances to use in one image
    MAX_GT_INSTANCES: 1 #MDH

    # Image mean (RGB)
    MEAN_PIXEL: !expr c(90, 91, 70, 141)
    VARIANCE:   !expr c(3587, 3146, 2022, 6594)
    
    IMAGES_PER_GPU: 2
    GPU_COUNT: 1
    
testing:
  IMAGE_SIZE: 224
  EPOCHS: 100
  N_STEPS: 1
  BATCH_SIZE: 4
  AMT_TRAIN: 256
  AMT_VAL: 80
  
pre_chip:
    # Image and mask locations for already chipped image iterator
    TRAIN_IMG: 'C:/Users/matthew.d.harris/UNET_MRCNN_IMAGERY/OUTPUT/SARA_CROP_3chan_tif_1ft_train/tif'
    TRAIN_MSK: 'C:/Users/matthew.d.harris/UNET_MRCNN_IMAGERY/OUTPUT/SARA_CROP_3chan_tif_1ft_train/polygon'
    VAL_IMG:   'C:/Users/matthew.d.harris/UNET_MRCNN_IMAGERY/OUTPUT/SARA_CROP_3chan_tif_1ft_test/tif'
    VAL_MSK:   'C:/Users/matthew.d.harris/UNET_MRCNN_IMAGERY/OUTPUT/SARA_CROP_3chan_tif_1ft_test/polygon'


