default:
    IMAGE_SIZE: 128
    N_CHANNELS: 3
    USE_HILL: True
    NORM_IMAGES: True
    NUM_CLASSES: 1
    CLASS_NAME: "Structures"

    EPOCHS: 5
    N_STEPS: 1
    BATCH_SIZE: 2
    DROPOUT: 0.20

    AMT_TRAIN: 280
    AMT_VAL: 50

    # Image and mask locations for single image inifinite chip generator
    TRAIN_IMG: 'C:/Project_files/SARA/TIFF/SARA_1ft/SARA_1ft_CROP.tif'
    TRAIN_MSK: 'C:/Project_files/SARA/IMAGE_TILES/binary_masks_1ft/SARA_2_mask.tif'
    VAL_IMG:   'C:/Project_files/SARA/TIFF/SARA_1ft/SARA_1ft_CROP.tif'
    VAL_MSK:   'C:/Project_files/SARA/IMAGE_TILES/binary_masks_1ft/SARA_2_mask.tif'
    
    # Image and mask locations for already chipped image iterator
    #TRAIN_IMG: 'C:/Users/matthew.d.harris/UNET_MRCNN_IMAGERY/OUTPUT/SARA_CROP_3chan_tif_1ft_train/tif'
    #TRAIN_MSK: 'C:/Users/matthew.d.harris/UNET_MRCNN_IMAGERY/OUTPUT/SARA_CROP_3chan_tif_1ft_train/polygon'
    #VAL_IMG:   'C:/Users/matthew.d.harris/UNET_MRCNN_IMAGERY/OUTPUT/SARA_CROP_3chan_tif_1ft_test/tif'
    #VAL_MSK:   'C:/Users/matthew.d.harris/UNET_MRCNN_IMAGERY/OUTPUT/SARA_CROP_3chan_tif_1ft_test/polygon'
    SAVE_WEIGHTS_DIR: 'C:/Users/matthew.d.harris/ZF_UNET_224/weights'

    # Maximum number of ground truth instances to use in one image
    MAX_GT_INSTANCES: 1 #MDH

    # Image mean (RGB)
    MEAN_PIXEL: !expr c(90, 91, 70, 141)
    VARIANCE:   !expr c(3587, 3146, 2022, 6594)
    
    IMAGES_PER_GPU: 2
    GPU_COUNT: 1
    
testing:
  EPOCHS: 1
  N_STEPS: 1
  BATCH_SIZE: 2
  AMT_TRAIN: 100
  AMT_VAL: 30
